CREATE TABLE USERS (
    USERID                  VARCHAR2(20) , /* UserId */
    USERNAME                VARCHAR2(30) NOT NULL, /* Username */
    PASSWORD                VARCHAR2(4) NOT NULL, /* password */
    TRANSACTION_PASSWORD    VARCHAR2(40) NOT NULL, /* Transaction_password */
    CONSTRAINT USERS_PK PRIMARY KEY(USERID)
);

COMMENT ON TABLE USERS IS '사용자 목록';
COMMENT ON COLUMN USERS.USERID IS '아이디';
COMMENT ON COLUMN USERS.USERNAME IS '사용자명';
COMMENT ON COLUMN USERS.PASSWORD IS '비밀번호(숫자 4자리)';
COMMENT ON COLUMN USERS.TRANSACTION_PASSWORD IS '결제 비밀번호';





CREATE TABLE LOGS (
    LOGNO               NUMBER, /* LogNo */
    UserId              VARCHAR2(20), /* UserId */
    TRANSACTION_DATE    TIMESTAMP NOT NULL, /* Transaction_date */
    deposit             NUMBER DEFAULT 0, /* deposit */
    mall                VARCHAR2(100) NOT NULL, /* mall */
    means               VARCHAR2(15) NOT NULL, /* means */
    CONSTRAINT LOGS_PK PRIMARY key(LOGNO)
);

COMMENT ON TABLE LOGS IS '거래내역';
COMMENT ON COLUMN LOGS.LOGNO IS '고유번호';
COMMENT ON COLUMN LOGS.UserId IS '아이디';
COMMENT ON COLUMN LOGS.TRANSACTION_DATE IS '거래 날짜';
COMMENT ON COLUMN LOGS.deposit IS '거래 액수';
COMMENT ON COLUMN LOGS.mall IS '거래처';
COMMENT ON COLUMN LOGS.means IS '결제 수단';

CREATE SEQUENCE SEQ_LOGNO START WITH 1 INCREMENT BY 1 ORDER;





CREATE TABLE ACCOUNTS(
    ACCOUNT_NUMBER  VARCHAR2(20),
    USERID          VARCHAR2(20),
    BALANCE         NUMBER DEFAULT 0,
    CONSTRAINT ACCOUNTS_PK PRIMARY KEY(ACCOUNT_NUMBER),
    CONSTRAINT ACCOUNTS_FK_TO_USERS FOREIGN KEY(USERID) REFERENCES USERS(USERID) ON DELETE SET NULL
);

COMMENT ON TABLE ACCOUNTS IS '계좌';
COMMENT ON COLUMN ACCOUNTS.ACCOUNT_NUMBER IS '계좌번호';
COMMENT ON COLUMN ACCOUNTS.USERID IS '아이디';
COMMENT ON COLUMN ACCOUNTS.BALANCE IS '잔고';





CREATE TABLE CARDS (
    CARD_NUMBER VARCHAR2(20) NOT NULL, /* Card_number */
    ACCOUNT_NUMBER VARCHAR2(20), /* Account_number */
    USERID varchar2(20), /* UserId */
    CVS varchar2(3) NOT NULL, /* CVS */
    CONSTRAINT CARDS_PK PRIMARY KEY(CARD_NUMBER),
    CONSTRAINT CARDS_FK_TO_USERS FOREIGN KEY(USERID) REFERENCES USERS(USERID),
    CONSTRAINT CARDS_FK_TO_ACCOUNTS FOREIGN KEY(ACCOUNT_NUMBER) REFERENCES ACCOUNTS(ACCOUNT_NUMBER)
);

COMMENT ON TABLE CARDS IS '카드';
COMMENT ON COLUMN CARDS.CARD_NUMBER IS '카드 번호';
COMMENT ON COLUMN CARDS.ACCOUNT_NUMBER IS '카드와 연결된 계좌번호';
COMMENT ON COLUMN CARDS.USERID IS '아이디';
COMMENT ON COLUMN CARDS.CVS IS '3자리 인식 번호';

